# Generated by Django 5.0.4 on 2025-04-16 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "id_or_passport",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("Twitter", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Kenya", "Kenya"),
                            ("Uganda", "Uganda"),
                            ("Tanzania", "Tanzania"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Nearest city or coordinates", max_length=255
                    ),
                ),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "size_sq_km",
                    models.FloatField(
                        blank=True, help_text="Size in square kilometers", null=True
                    ),
                ),
                ("journey_description", models.TextField()),
                ("history", models.TextField()),
                (
                    "flora_and_fauna",
                    models.TextField(
                        help_text="Details about wildlife and plants seen at the park"
                    ),
                ),
                (
                    "climate",
                    models.TextField(
                        blank=True, help_text="Weather and best time to visit"
                    ),
                ),
                (
                    "booking_info",
                    models.TextField(help_text="How visitors can book or contact you"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="ParkList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("park_image", models.ImageField(upload_to="park_images/")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "important_information",
                    models.TextField(
                        help_text="Rules, regulations, health precautions"
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_information",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HowToGetThere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("by_road", models.TextField()),
                ("by_air", models.TextField()),
                ("journey_details", models.TextField()),
                (
                    "park",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_info",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Visitor"),
                            ("foreign", "Foreign Visitor"),
                            ("child", "Child"),
                            ("student", "Student"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_fees",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BookPark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="park_data.customer",
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookings",
                        to="park_data.park",
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("contact_info", models.TextField()),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Park_Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("highlights", models.TextField()),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="park_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="park",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="park_data.parklist"
            ),
        ),
    ]
