# Generated by Django 5.0.4 on 2025-04-12 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("country", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "location",
                    models.CharField(
                        help_text="Nearest city or coordinates", max_length=255
                    ),
                ),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "size_sq_km",
                    models.FloatField(
                        blank=True, help_text="Size in square kilometers", null=True
                    ),
                ),
                ("description", models.TextField()),
                ("history", models.TextField()),
                ("highlights", models.TextField()),
                (
                    "flora_and_fauna",
                    models.TextField(help_text="Details about wildlife and plants"),
                ),
                (
                    "climate",
                    models.TextField(
                        blank=True, help_text="Weather and best time to visit"
                    ),
                ),
                (
                    "important_information",
                    models.TextField(
                        help_text="Rules, regulations, health precautions"
                    ),
                ),
                (
                    "booking_info",
                    models.TextField(help_text="How visitors can book or contact you"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HowToGetThere",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("by_road", models.TextField()),
                ("by_air", models.TextField()),
                ("journey_details", models.TextField()),
                (
                    "park",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="travel_info",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryFee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_type",
                    models.CharField(
                        choices=[
                            ("local", "Local Visitor"),
                            ("foreign", "Foreign Visitor"),
                            ("child", "Child"),
                            ("student", "Student"),
                        ],
                        max_length=50,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=8)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entry_fees",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                ("contact_info", models.TextField()),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="accommodations",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ParkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="park_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
    ]
