# Generated by Django 5.0.4 on 2025-04-18 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Accommodation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hotel_name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="park_images/")),
                (
                    "fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                (
                    "price_per_night",
                    models.DecimalField(decimal_places=2, max_digits=8),
                ),
                (
                    "meal_cost",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
                ),
                ("contact_info", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("main_image", models.ImageField(upload_to="animal_profiles/")),
                (
                    "habitat_image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_profiles/"
                    ),
                ),
                (
                    "habitat_image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_profiles/"
                    ),
                ),
                (
                    "habitat_image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_profiles/"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateField(auto_now_add=True)),
                ("first_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("last_name", models.CharField(max_length=100)),
                (
                    "id_or_passport",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("country", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
                ("facebook", models.URLField(blank=True, null=True)),
                ("instagram", models.URLField(blank=True, null=True)),
                ("Twitter", models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "important_information",
                    models.TextField(
                        help_text="Rules, regulations, health precautions"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    models.CharField(
                        choices=[
                            ("Kenya", "Kenya"),
                            ("Uganda", "Uganda"),
                            ("Tanzania", "Tanzania"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        help_text="Nearest city or coordinates", max_length=255
                    ),
                ),
                ("established_date", models.DateField(blank=True, null=True)),
                (
                    "size_sq_km",
                    models.FloatField(
                        blank=True, help_text="Size in square kilometers", null=True
                    ),
                ),
                ("journey_description", models.TextField()),
                ("history", models.TextField()),
                (
                    "flora_and_fauna",
                    models.TextField(
                        help_text="Details about wildlife and plants seen at the park"
                    ),
                ),
                (
                    "climate",
                    models.TextField(
                        blank=True, help_text="Weather and best time to visit"
                    ),
                ),
                (
                    "booking_info",
                    models.TextField(help_text="How visitors can book or contact you"),
                ),
                ("slug", models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Park_Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("highlights", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ParkImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="park_images/")),
                ("caption", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="ParkList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("park_image", models.ImageField(upload_to="park_images/")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Tour_Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("message", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "Booking",
                "verbose_name_plural": "Bookings",
                "ordering": ["-created"],
            },
        ),
        migrations.CreateModel(
            name="TourBooking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nights", models.PositiveIntegerField(default=2)),
                ("van_days", models.PositiveIntegerField(default=1)),
                (
                    "hotel_rate",
                    models.DecimalField(decimal_places=2, default=4000, max_digits=10),
                ),
                (
                    "van_rate",
                    models.DecimalField(decimal_places=2, default=3500, max_digits=10),
                ),
                (
                    "park_fee",
                    models.DecimalField(decimal_places=2, default=1200, max_digits=10),
                ),
                ("is_paid", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="TouringVan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("van_name", models.CharField(max_length=200)),
                (
                    "van_type",
                    models.CharField(
                        choices=[
                            ("4x4", "4x4"),
                            ("Minibus", "Minibus"),
                            ("SUV", "SUV"),
                        ],
                        max_length=100,
                    ),
                ),
                ("seating_capacity", models.PositiveIntegerField()),
                ("availability", models.BooleanField(default=True)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("driver_included", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="van_images/"),
                ),
                ("contact_info", models.TextField()),
            ],
        ),
    ]
