# Generated by Django 5.0.4 on 2025-04-18 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("park_data", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="person",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="information",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="important_information",
                to="park_data.park",
            ),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="accommodations",
                to="park_data.park",
            ),
        ),
        migrations.AddField(
            model_name="park_highlight",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="highlights",
                to="park_data.park",
            ),
        ),
        migrations.AddField(
            model_name="parkimage",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="park_data.park",
            ),
        ),
        migrations.AddField(
            model_name="park",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="park_data.parklist"
            ),
        ),
        migrations.AddField(
            model_name="tour_booking",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="park_data.customer"
            ),
        ),
        migrations.AddField(
            model_name="tour_booking",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="park_data.park",
            ),
        ),
        migrations.AddField(
            model_name="tourbooking",
            name="customer_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="park_data.customer"
            ),
        ),
        migrations.AddField(
            model_name="touringvan",
            name="park",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vans",
                to="park_data.park",
            ),
        ),
        migrations.AddField(
            model_name="tour_booking",
            name="van",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="park_data.touringvan",
            ),
        ),
    ]
