# Generated by Django 5.0.4 on 2025-04-12 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accommodation",
            old_name="name",
            new_name="hotel_name",
        ),
    ]
