# Generated by Django 5.0.4 on 2025-04-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookpark",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
