# Generated by Django 5.0.4 on 2025-04-12 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0002_rename_name_accommodation_hotel_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="park",
            name="highlights",
        ),
        migrations.RemoveField(
            model_name="park",
            name="important_information",
        ),
        migrations.CreateModel(
            name="Information",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "important_information",
                    models.TextField(
                        help_text="Rules, regulations, health precautions"
                    ),
                ),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="important_information",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Park_Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("highlights", models.TextField()),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
    ]
