# Generated by Django 5.0.4 on 2025-04-17 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0002_bookpark_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="accommodation",
            name="fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="image",
            field=models.ImageField(blank=True, upload_to="park_images/"),
        ),
        migrations.AddField(
            model_name="accommodation",
            name="meal_cost",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
