# Generated by Django 5.0.4 on 2025-04-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0003_remove_park_highlights_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="park",
            name="flora_and_fauna",
            field=models.TextField(
                help_text="Details about wildlife and plants seen at the park"
            ),
        ),
    ]
