# Generated by Django 5.0.4 on 2025-04-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0003_catalog"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="entry_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
