# Generated by Django 5.0.4 on 2025-04-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0003_accommodation_fee_accommodation_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TouringVan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("van_name", models.CharField(max_length=200)),
                (
                    "van_type",
                    models.CharField(
                        choices=[
                            ("4x4", "4x4"),
                            ("Minibus", "Minibus"),
                            ("SUV", "SUV"),
                        ],
                        max_length=100,
                    ),
                ),
                ("seating_capacity", models.PositiveIntegerField()),
                ("availability", models.BooleanField(default=True)),
                ("daily_rate", models.DecimalField(decimal_places=2, max_digits=8)),
                ("driver_included", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="van_images/"),
                ),
                ("contact_info", models.TextField()),
                (
                    "park",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vans",
                        to="park_data.park",
                    ),
                ),
            ],
        ),
    ]
