# Generated by Django 5.0.4 on 2025-04-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0004_touringvan"),
    ]

    operations = [
        migrations.CreateModel(
            name="Animal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("main_image", models.ImageField(upload_to="animal_profiles/")),
                (
                    "habitat_image1",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_profiles/"
                    ),
                ),
                (
                    "habitat_image2",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_profiles/"
                    ),
                ),
                (
                    "habitat_image3",
                    models.ImageField(
                        blank=True, null=True, upload_to="animal_profiles/"
                    ),
                ),
            ],
        ),
    ]
