# Generated by Django 5.0.4 on 2025-04-20 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0004_park_entry_fee"),
    ]

    operations = [
        migrations.CreateModel(
            name="Compliment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("message", models.TextField()),
                ("repy", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
