# Generated by Django 5.0.4 on 2025-04-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0004_park_slug_alter_park_flora_and_fauna"),
    ]

    operations = [
        migrations.RenameField(
            model_name="park",
            old_name="description",
            new_name="journey_description",
        ),
        migrations.AlterField(
            model_name="park",
            name="country",
            field=models.CharField(
                choices=[
                    ("Kenya", "Kenya"),
                    ("Uganda", "Uganda"),
                    ("Tanzania", "Tanzania"),
                ],
                max_length=100,
            ),
        ),
    ]
