# Generated by Django 5.0.4 on 2025-04-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0005_rename_description_park_journey_description_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParkList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("park_image", models.ImageField(upload_to="park_images/")),
                ("name", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="park",
            name="name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="park_data.parklist"
            ),
        ),
    ]
