# Generated by Django 5.0.4 on 2025-04-18 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0005_animal"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
