# Generated by Django 5.0.4 on 2025-04-15 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0006_parklist_alter_park_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="park",
            name="name",
        ),
    ]
