# Generated by Django 5.0.4 on 2025-04-15 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0007_remove_park_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="park",
            name="name",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="park_data.parklist",
            ),
        ),
    ]
