# Generated by Django 5.0.4 on 2025-04-15 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("park_data", "0009_customer_alter_park_name_booking"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="customer",
            name="phone_number",
            field=models.CharField(max_length=20),
        ),
    ]
